# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Database(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, database_file: str=None):  # noqa: E501
        """Database - a model defined in Swagger

        :param database_file: The database_file of this Database.  # noqa: E501
        :type database_file: str
        """
        self.swagger_types = {
            'database_file': str
        }

        self.attribute_map = {
            'database_file': 'Database File'
        }
        self._database_file = database_file

    @classmethod
    def from_dict(cls, dikt) -> 'Database':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The database of this Database.  # noqa: E501
        :rtype: Database
        """
        return util.deserialize_model(dikt, cls)

    @property
    def database_file(self) -> str:
        """Gets the database_file of this Database.

        The database file containing employee details.  # noqa: E501

        :return: The database_file of this Database.
        :rtype: str
        """
        return self._database_file

    @database_file.setter
    def database_file(self, database_file: str):
        """Sets the database_file of this Database.

        The database file containing employee details.  # noqa: E501

        :param database_file: The database_file of this Database.
        :type database_file: str
        """

        self._database_file = database_file
