# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrganizationInformation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, member_name: str=None, organization_id: str=None, email: str=None, phone_number: int=None):  # noqa: E501
        """OrganizationInformation - a model defined in Swagger

        :param member_name: The member_name of this OrganizationInformation.  # noqa: E501
        :type member_name: str
        :param organization_id: The organization_id of this OrganizationInformation.  # noqa: E501
        :type organization_id: str
        :param email: The email of this OrganizationInformation.  # noqa: E501
        :type email: str
        :param phone_number: The phone_number of this OrganizationInformation.  # noqa: E501
        :type phone_number: int
        """
        self.swagger_types = {
            'member_name': str,
            'organization_id': str,
            'email': str,
            'phone_number': int
        }

        self.attribute_map = {
            'member_name': 'member_name',
            'organization_id': 'organization_id',
            'email': 'email',
            'phone_number': 'phone_number'
        }
        self._member_name = member_name
        self._organization_id = organization_id
        self._email = email
        self._phone_number = phone_number

    @classmethod
    def from_dict(cls, dikt) -> 'OrganizationInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Organization Information of this OrganizationInformation.  # noqa: E501
        :rtype: OrganizationInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def member_name(self) -> str:
        """Gets the member_name of this OrganizationInformation.

        The name of the Admin  # noqa: E501

        :return: The member_name of this OrganizationInformation.
        :rtype: str
        """
        return self._member_name

    @member_name.setter
    def member_name(self, member_name: str):
        """Sets the member_name of this OrganizationInformation.

        The name of the Admin  # noqa: E501

        :param member_name: The member_name of this OrganizationInformation.
        :type member_name: str
        """

        self._member_name = member_name

    @property
    def organization_id(self) -> str:
        """Gets the organization_id of this OrganizationInformation.

        The ID of the Organization, the member belongs to.  # noqa: E501

        :return: The organization_id of this OrganizationInformation.
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id: str):
        """Sets the organization_id of this OrganizationInformation.

        The ID of the Organization, the member belongs to.  # noqa: E501

        :param organization_id: The organization_id of this OrganizationInformation.
        :type organization_id: str
        """

        self._organization_id = organization_id

    @property
    def email(self) -> str:
        """Gets the email of this OrganizationInformation.

        The email of the Admin  # noqa: E501

        :return: The email of this OrganizationInformation.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this OrganizationInformation.

        The email of the Admin  # noqa: E501

        :param email: The email of this OrganizationInformation.
        :type email: str
        """

        self._email = email

    @property
    def phone_number(self) -> int:
        """Gets the phone_number of this OrganizationInformation.

        The phone number of the admin  # noqa: E501

        :return: The phone_number of this OrganizationInformation.
        :rtype: int
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: int):
        """Sets the phone_number of this OrganizationInformation.

        The phone number of the admin  # noqa: E501

        :param phone_number: The phone_number of this OrganizationInformation.
        :type phone_number: int
        """

        self._phone_number = phone_number
